/*
 * Generated by XDoclet - Do not edit!
 */
package org.openempi.ics.pids;

import java.util.List;

import javax.ejb.EJBException;

import org.openempi.data.Person;

/**
 * Remote interface for IdentityService.
 * @wtp generated
 */
public interface IdentityService
   extends javax.ejb.EJBObject
{

   public List getProfile(org.openempi.data.PersonIdentifier pid)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public List findPersons(Person person)
   	  throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;
   
   public List findCandidates(Person person)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public List findCandidates(Person person, double confidence)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public List findCandidates(Person person, int max)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public List findCandidates(Person person, double confidence, int max)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public List getProfileList(List identifiers)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public Person getPersonByOid(String oid)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public Person getPersonByOid(int oid)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public int queryStart(Person person, double confidence)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public List queryNext(int ref, int howMany)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public void queryEnd(int ref)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

   public Person getPersonByCorpId(String clientId, String corpId)
      throws org.openempi.ics.pids.IdentityServiceException, java.rmi.RemoteException;

}
