/*
 * Generated by XDoclet - Do not edit!
 */
package org.openempi.ics.pids;

/**
 * Home interface for IdentityService.
 */
public interface IdentityServiceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/IdentityService";
   public static final String JNDI_NAME="ejb/IdentityService";

   public IdentityService create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
