/*
 * Generated by XDoclet - Do not edit!
 */
package org.openempi.ics.pids;

/**
 * Home interface for PersonIdService.
 */
public interface PersonIdServiceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PersonIdService";
   public static final String JNDI_NAME="ejb/PersonIdService";

   public PersonIdService create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
