/*
 * Generated by XDoclet - Do not edit!
 */
package org.openempi.ils.ejb;

/**
 * Home interface for IlsService.
 */
public interface IlsServiceHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/IlsService";
   public static final String JNDI_NAME="ejb/IlsService";

   public IlsService create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
